export const CHANGE_NAME = 'auftrag/CHANGE_NAME'
export const CHANGE_PLZ = 'auftrag/CHANGE_PLZ'
export const ADD_OBJECT = 'auftrag/ADD_OBJECT'
export const CHANGE_OBJECT = 'auftrag/CHANGE_OBJECT'
export const REMOVE_OBJECT = 'auftrag/REMOVE_OBJECT'
export const CHANGE_AUSGEHANDELTER_PREIS = 'auftrag/CHANGE_AUSGEHANDELTER_PREIS'
export const CHANGE_STANDORT = 'auftrag/CHANGE_STANDORT'
export const CHANGE_NOTIZ = 'auftrag/CHANGE_NOTIZ'
